version = 0.1

[default.deploy.parameters]
stack_name = "pwa-m3u-youtube-extractor"
resolve_s3 = true
s3_prefix = "pwa-m3u-youtube-extractor"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
