version = 0.1

[default.deploy.parameters]
stack_name = "stream-analyzer"
resolve_s3 = true
s3_prefix = "stream-analyzer"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
